openapi: 3.0.1
info:
  title: monster-abishai-blue
  x-cortex-tag: monster-abishai-blue
x-cortex-custom-data:
  alignment: lawful-evil
  challenge_rating: 9
  legendary: true
  source: dnd-5e
  type: fiend
x-cortex-owners:
- email: bestiary@dnd.com
x-cortex-tag: monster-abishai-blue
x-cortex-type: monster
